<a href="https://colab.research.google.com/github/VISHAL2077/SML_Assignments/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

data = pd.read_csv('life_expectancy.csv')

In [46]:
print(data.head())
print(data.columns.tolist())

       Country  Year      Status  Life expectancy   Adult Mortality  \
0  Afghanistan  2015  Developing              65.0            263.0   
1  Afghanistan  2014  Developing              59.9            271.0   
2  Afghanistan  2013  Developing              59.9            268.0   
3  Afghanistan  2012  Developing              59.5            272.0   
4  Afghanistan  2011  Developing              59.2            275.0   

   infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   ...  \
0             62     0.01               71.279624         65.0      1154  ...   
1             64     0.01               73.523582         62.0       492  ...   
2             66     0.01               73.219243         64.0       430  ...   
3             69     0.01               78.184215         67.0      2787  ...   
4             71     0.01                7.097109         68.0      3013  ...   

   Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  Population  \
0    6.

In [45]:
print(data.dtypes)

categorical_cols = data.select_dtypes(include=['object']).columns.tolist()
print("Categorical columns:", categorical_cols)

Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult Mortality                    float64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
 BMI                               float64
under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
 HIV/AIDS                          float64
GDP                                float64
Population                         float64
 thinness  1-19 years              float64
 thinness 5-9 years                float64
Income composition of resources    float64
Schooling                          float64
dtype: object
Categorical columns: ['Country', 'Status

In [44]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

data = pd.read_csv('life_expectancy.csv')

categorical_cols = data.select_dtypes(include=['object']).columns.tolist()

data_encoded = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

X = data_encoded.drop('Life expectancy ', axis=1)
y = data_encoded['Life expectancy ']

bins = [0, 50, 60, 70, 80, 90, 100]
labels = [0, 1, 2, 3, 4, 5]

y_binned = pd.cut(y, bins=bins, labels=labels, include_lowest=True)

data_cleaned = data_encoded.dropna()
X_cleaned = data_cleaned.drop('Life expectancy ', axis=1)
y_cleaned = data_cleaned['Life expectancy ']

y_cleaned_binned = pd.cut(y_cleaned, bins=bins, labels=labels, include_lowest=True)

X_train, X_test, y_train, y_test = train_test_split(X_cleaned, y_cleaned_binned, test_size=0.2, random_state=42)

pipelines = {
    'Logistic Regression': Pipeline([('imputer', SimpleImputer(strategy='mean')),
                                     ('model', LogisticRegression(max_iter=2000))]),
    'Random Forest': Pipeline([('imputer', SimpleImputer(strategy='mean')),
                               ('model', RandomForestClassifier())]),
    'SVC': Pipeline([('imputer', SimpleImputer(strategy='mean')),
                     ('model', SVC())]),
    'KNN': Pipeline([('imputer', SimpleImputer(strategy='mean')),
                     ('model', KNeighborsClassifier())]),
    'Decision Tree': Pipeline([('imputer', SimpleImputer(strategy='mean')),
                               ('model', DecisionTreeClassifier())])
}

for name, pipeline in pipelines.items():
    pipeline.fit(X_train, y_train)
    preds = pipeline.predict(X_test)

    cm = confusion_matrix(y_test, preds)
    accuracy = accuracy_score(y_test, preds)
    precision = precision_score(y_test, preds, average='weighted', zero_division=0)
    recall = recall_score(y_test, preds, average='weighted', zero_division=0)
    f1 = f1_score(y_test, preds, average='weighted', zero_division=0)

    print(f"{name} Metrics:")
    print(f"Confusion Matrix:\n{cm}")
    print(f"Accuracy: {accuracy:.2f}")
    print(f"Precision: {precision:.2f}")
    print(f"Recall: {recall:.2f}")
    print(f"F1 Score: {f1:.2f}\n")

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression Metrics:
Confusion Matrix:
[[  0   0   5   3   0]
 [  0   0  40   7   0]
 [  0   0  41  39   0]
 [  0   1  46 127   2]
 [  0   0   1  12   6]]
Accuracy: 0.53
Precision: 0.48
Recall: 0.53
F1 Score: 0.49

Random Forest Metrics:
Confusion Matrix:
[[  5   3   0   0   0]
 [  1  43   3   0   0]
 [  0   3  74   3   0]
 [  0   0   3 172   1]
 [  0   0   0   3  16]]
Accuracy: 0.94
Precision: 0.94
Recall: 0.94
F1 Score: 0.94

SVC Metrics:
Confusion Matrix:
[[  0   0   0   8   0]
 [  0   0   1  46   0]
 [  0   0   6  74   0]
 [  0   0   3 173   0]
 [  0   0   0  19   0]]
Accuracy: 0.54
Precision: 0.43
Recall: 0.54
F1 Score: 0.40

KNN Metrics:
Confusion Matrix:
[[ 0  1  4  3  0]
 [ 3  7 26 10  1]
 [ 3 14 36 26  1]
 [ 3 27 48 95  3]
 [ 1  3  1 11  3]]
Accuracy: 0.43
Precision: 0.47
Recall: 0.43
F1 Score: 0.44

Decision Tree Metrics:
Confusion Matrix:
[[  5   3   0   0   0]
 [  4  40   3   0   0]
 [  0   4  73   3   0]
 [  0   0   5 168   3]
 [  0   0   0   2  17]]
Accuracy: 0.92

In [43]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

data = pd.read_csv('life_expectancy.csv')

categorical_cols = data.select_dtypes(include=['object']).columns.tolist()

data_encoded = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

X = data_encoded.drop('Life expectancy ', axis=1)
y = data_encoded['Life expectancy ']

data_cleaned = data_encoded.dropna()
X_cleaned = data_cleaned.drop('Life expectancy ', axis=1)
y_cleaned = data_cleaned['Life expectancy ']

X_train, X_test, y_train, y_test = train_test_split(X_cleaned, y_cleaned, test_size=0.2, random_state=42)

pipelines = {
    'Linear Regression': Pipeline([('imputer', SimpleImputer(strategy='mean')),
                                   ('model', LinearRegression())]),
    'KNN': Pipeline([('imputer', SimpleImputer(strategy='mean')),
                     ('model', KNeighborsRegressor())]),
    'Decision Tree': Pipeline([('imputer', SimpleImputer(strategy='mean')),
                               ('model', DecisionTreeRegressor())]),
    'Random Forest': Pipeline([('imputer', SimpleImputer(strategy='mean')),
                               ('model', RandomForestRegressor())]),
    'SVR': Pipeline([('imputer', SimpleImputer(strategy='mean')),
                     ('model', SVR())])
}

predictions = {}
for name, pipeline in pipelines.items():
    pipeline.fit(X_train, y_train)
    preds = pipeline.predict(X_test)

    predictions[name] = preds

    rmse = np.sqrt(mean_squared_error(y_test, preds))
    mae = mean_absolute_error(y_test, preds)
    r2 = r2_score(y_test, preds)

    print(f"{name} - RMSE: {rmse:.2f}, MAE: {mae:.2f}, R^2: {r2:.2f}")

Linear Regression - RMSE: 1.91, MAE: 1.13, R^2: 0.95
KNN - RMSE: 8.40, MAE: 6.67, R^2: 0.01
Decision Tree - RMSE: 2.92, MAE: 1.55, R^2: 0.88
Random Forest - RMSE: 1.86, MAE: 1.10, R^2: 0.95
SVR - RMSE: 8.51, MAE: 6.42, R^2: -0.02
